#!/usr/bin/env node

import { program } from './_shared.js';
import { registerAnalyze } from './commands/analyze.js';
import { registerDoctor } from './commands/doctor.js';
import { registerCi } from './commands/ci.js';
import { registerDiff } from './commands/diff.js';
import { registerFix } from './commands/fix.js';
import { registerFile } from './commands/file.js';
import { registerExplain } from './commands/explain.js';
import { registerDiagram } from './commands/diagram.js';
import { registerStructure } from './commands/structure.js';
import { registerDependencies } from './commands/dependencies.js';
import { registerHotspots } from './commands/hotspots.js';
import { registerCoupling } from './commands/coupling.js';
import { registerPrDiff } from './commands/prDiff.js';
import { registerWorkspaces } from './commands/workspaces.js';
import { registerOutdated } from './commands/outdated.js';
import { registerAudit } from './commands/audit.js';
import { registerUpgrade } from './commands/upgrade.js';
import { registerSearch } from './commands/search.js';
import { registerCoverage } from './commands/coverage.js';
import { registerMcp } from './commands/mcp.js';
import { registerBadge } from './commands/badge.js';
import { registerHelp } from './commands/help.js';

registerAnalyze();
registerDoctor();
registerCi();
registerDiff();
registerFix();
registerFile();
registerExplain();
registerDiagram();
registerStructure();
registerDependencies();
registerHotspots();
registerCoupling();
registerPrDiff();
registerWorkspaces();
registerOutdated();
registerAudit();
registerUpgrade();
registerSearch();
registerCoverage();
registerMcp();
registerBadge();
registerHelp();

program.parse();
