export { reportDiagram, reportStructure } from './consoleArchitectureReporter.js';
export { reportAnalysis } from './consoleAnalysisReporter.js';
export { reportAudit } from './consoleAuditReporter.js';
export { reportCi } from './consoleCiReporter.js';
export { reportCoupling } from './consoleCouplingReporter.js';
export { reportDependencies } from './consoleDependencyReporter.js';
export { reportDiff } from './consoleDiffReporter.js';
export { reportExplanation } from './consoleExplanationReporter.js';
export { reportDetectedIssues, reportFixResults } from './consoleFixReporter.js';
export { reportExplainIssue, reportFixSuggest } from './consoleFixGuidanceReporter.js';
export { reportFileInspection } from './consoleFileReporter.js';
export { reportHealth } from './consoleHealthReporter.js';
export type { ReportHealthOptions } from './consoleHealthReporter.js';
export { reportHotspots } from './consoleHotspotReporter.js';
export { reportImpact } from './consoleImpactReporter.js';
export { reportOutdated } from './consoleOutdatedReporter.js';
export { reportPrDiff } from './consolePrDiffReporter.js';
export { reportReview } from './consoleReviewReporter.js';
export { reportUpgrade } from './consoleUpgradeReporter.js';
export { reportCoverage } from './consoleCoverageReporter.js';
export { reportWorkspaces } from './consoleWorkspaceReporter.js';
