import type { ReportControlsMetadata } from '../core/reportScope.js';

const STYLE = `
:root {
  color-scheme: light dark;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0;
  padding: 2rem;
  max-width: 1100px;
  margin-inline: auto;
  line-height: 1.5;
  color: #222;
  background: #fafafa;
}
@media (prefers-color-scheme: dark) {
  body { color: #ddd; background: #181818; }
  .card { background: #222; border-color: #333; }
  table { background: #222; }
  th { background: #2a2a2a; }
  tr:nth-child(even) td { background: #1f1f1f; }
  code { background: #2a2a2a; }
  a { color: #6cb6ff; }
}
h1 { margin-top: 0; font-size: 1.6rem; }
h2 { margin-top: 2rem; font-size: 1.2rem; border-bottom: 1px solid #ccc; padding-bottom: 0.3rem; }
.card {
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 1rem 1.2rem;
  margin-bottom: 1rem;
}
.score { font-size: 2.5rem; font-weight: 700; }
.grade-A, .grade-A\\+ { color: #1a8a4a; }
.grade-B { color: #4a8a1a; }
.grade-C { color: #c79100; }
.grade-D { color: #d6582d; }
.grade-F { color: #d63333; }
table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; background: #fff; }
th, td { padding: 0.4rem 0.6rem; text-align: left; border-bottom: 1px solid #eee; }
th { background: #f3f3f3; font-weight: 600; }
tr:nth-child(even) td { background: #f9f9f9; }
code { background: #f0f0f0; padding: 0.05em 0.4em; border-radius: 3px; font-size: 0.95em; }
.severity-error { color: #d63333; }
.severity-warning { color: #c79100; }
.severity-info { color: #4a6a8a; }
.muted { color: #888; font-size: 0.9rem; }
.verdict-ok { color: #1a8a4a; font-weight: 700; }
.verdict-review { color: #c79100; font-weight: 700; }
.verdict-block { color: #d63333; font-weight: 700; }
.right { text-align: right; }
.tag { display: inline-block; padding: 0.05em 0.5em; border-radius: 3px; background: #e8e8e8; font-size: 0.85em; }
.tag-new { background: #ffd6d6; color: #8a0000; }
.tag-expanded { background: #fff3c4; color: #6a4a00; }
`.trim();

/** Wrap inner HTML in a complete document. Title is required for accessibility. */
export function htmlShell(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${STYLE}</style>
</head>
<body>
${bodyHtml}
<footer class="muted" style="margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ccc;">
Generated by <a href="https://github.com/abhiyoheswaran1/projscan">projscan</a> at ${new Date().toISOString()}
</footer>
</body>
</html>`;
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function severityIcon(s: 'info' | 'warning' | 'error'): string {
  switch (s) {
    case 'error':
      return '✕';
    case 'warning':
      return '!';
    default:
      return 'i';
  }
}

export function signed(n: number): string {
  return n >= 0 ? `+${n}` : String(n);
}

export function reportControlsHtml(reportControls: ReportControlsMetadata | undefined): string {
  if (!reportControls) return '';
  const redaction = reportControls.redactPaths
    ? (reportControls.pathLabelFormat ?? 'enabled')
    : 'disabled';
  return `<div class="card">
<strong>Report controls:</strong> active; scopes: ${reportControls.scopeCount}; path redaction: ${escapeHtml(redaction)}.
</div>`;
}
