const WEIGHT_FOUR_KEYWORDS = new Set([
  'warn',
  'warning',
  'warnings',
  'allow',
  'approve',
  'agentflight',
  'agentloop',
  'agentloopkit',
  'harness',
]);

const WEIGHT_THREE_KEYWORDS = new Set([
  'port',
  'ports',
  'eaddrinuse',
  'listen',
  'address',
  'permission',
  'denied',
  'enoent',
  'eresolve',
  'peer',
]);

const WEIGHT_TWO_KEYWORDS = new Set([
  'github',
  'action',
  'actions',
  'workflow',
  'workflows',
  'pipeline',
  'pipelines',
  'job',
  'jobs',
  'fail',
  'build',
  'builds',
  'lint',
  'typecheck',
  'typechecking',
  'install',
  'failed',
  'error',
  'errors',
  'failure',
  'failures',
  'debug',
  'stack',
  'trace',
  'production',
  'prod',
  'down',
  'outage',
  'incident',
  'triage',
  'runtime',
  'crash',
  'crashes',
  'crashing',
  'connection',
  'refused',
  'root',
  'cause',
  'returning',
  'returns',
  'log',
  'logs',
  '500',
  '502',
  '503',
  '504',
  '404',
  '403',
  '401',
  'proof',
  'prove',
  'regression',
  'verification',
  'verify',
  'smoke',
  'focused',
  'full',
  'test',
  'tests',
  'slow',
  'slower',
  'speed',
  'speedup',
  'faster',
  'benchmark',
  'benchmarks',
  'reproduce',
  'reproduces',
  'reproducing',
  'flake',
  'flaky',
  'flakes',
  'intermittent',
  'intermittently',
  'nondeterministic',
  'nondeterminism',
  'race',
  'condition',
  'stabilize',
  'stabilise',
  'quarantine',
]);

export function regressionPlanKeywordWeight(keyword: string): number | undefined {
  if (WEIGHT_FOUR_KEYWORDS.has(keyword)) return 4;
  if (WEIGHT_THREE_KEYWORDS.has(keyword)) return 3;
  if (WEIGHT_TWO_KEYWORDS.has(keyword)) return 2;
  if (keyword === 'pr') return 0.25;
  return undefined;
}
