const DATAFLOW_WEIGHT_TWO_KEYWORDS = new Set([
  'dataflow',
  'taint',
  'security',
  'injection',
  'secret',
  'secrets',
  'expose',
  'exposes',
  'exposed',
  'sanitize',
  'sanitized',
  'request',
  'data',
  'reach',
  'reaches',
  'exec',
  'auth',
  'bypass',
  'pii',
  'gdpr',
  'compliance',
  'personal',
  'customer',
  'email',
  'emails',
  'password',
  'token',
  'tokens',
  'leak',
  'leaks',
  'logged',
  'logging',
  'log',
  'logs',
  'store',
  'stores',
  'retention',
  'handled',
  'handles',
  'process',
  'processes',
  'processing',
]);

export function securityKeywordWeight(tool: string, keyword: string): number | undefined {
  if (tool !== 'projscan_dataflow') return undefined;
  return DATAFLOW_WEIGHT_TWO_KEYWORDS.has(keyword) ? 2 : undefined;
}
