const PRIVACY_WEIGHT_THREE_KEYWORDS = new Set([
  'privacy',
  'trust',
  'boundary',
  'env',
  'upload',
  'telemetry',
  'network',
  'offline',
  'leave',
  'machine',
]);

const PRIVACY_WEIGHT_TWO_KEYWORDS = new Set([
  'read',
  'code',
  'source',
  'values',
  'contact',
  'contacted',
  'write',
  'writes',
  'projscan',
]);

const UNDERSTAND_WEIGHT_TWO_KEYWORDS = new Set([
  'read',
  'summarize',
  'summary',
  'contract',
  'contracts',
  'api',
  'apis',
  'deprecate',
  'deprecates',
  'deprecated',
  'deprecation',
  'compatibility',
  'compatible',
  'architecture',
  'repo',
  'codebase',
  'service',
  'services',
  'main',
  'entrypoint',
  'entrypoints',
  'entry',
  'point',
  'important',
  'look',
  'first',
  'tour',
  'walk',
  'through',
  'new',
  'onboard',
  'onboarding',
  'run',
  'runs',
  'start',
  'app',
  'command',
  'commands',
  'dev',
  'server',
  'local',
  'locally',
  'docker',
  'compose',
  'npm',
  'script',
  'scripts',
  'test',
  'tests',
  'e2e',
  'unit',
  'integration',
  'storybook',
  'cypress',
  'playwright',
  'eslint',
  'prettier',
  'format',
  'lint',
  'typecheck',
  'typechecking',
  'verify',
  'verification',
  'proof',
  'prove',
  'checks',
  'environment',
  'environments',
  'variable',
  'variables',
  'missing',
  'required',
  'feature',
  'endpoint',
  'button',
  'put',
  'need',
  'change',
  'files',
  'add',
  'implement',
  'build',
  'create',
  'wire',
  'route',
  'component',
  'page',
  'screen',
  'view',
  'webhook',
  'auth',
  'login',
  'support',
  'checkout',
  'search',
  'doc',
  'docs',
  'document',
  'documentation',
  'readme',
  'examples',
  'example',
  'migration',
  'migrations',
  'migrate',
  'migrates',
  'database',
  'db',
  'schema',
  'table',
  'column',
  'seed',
  'seeds',
  'reset',
  'resets',
  'guide',
  'update',
  'updating',
]);

const FEEDBACK_WEIGHT_THREE_KEYWORDS = new Set([
  'feedback',
  'reviewer',
  'reviewers',
  'user',
  'users',
  'intake',
  'allow',
  'script',
  'scripts',
  'warning',
  'warnings',
  'tree',
  'sitter',
]);

const FEEDBACK_WEIGHT_TWO_KEYWORDS = new Set([
  'false',
  'positive',
  'unused',
  'exports',
  'alias',
  'import',
  'noisy',
  'noise',
  'caution',
  'signal',
  'doc',
  'docs',
  'output',
  'outputs',
  'wording',
  'confusing',
  'bigger',
  'demonstrated',
  'feature',
  'features',
  'breadth',
  'killer',
  'engineer',
  'engineers',
  'trust',
  'daily',
  'few',
  'workflow',
  'workflows',
  'overclaim',
  'overclaims',
  'wrong',
  'incorrect',
  'node',
  'gyp',
]);

export function trustFeedbackKeywordWeight(tool: string, keyword: string): number | undefined {
  if (tool === 'projscan_privacy_check') return privacyKeywordWeight(keyword);
  if (tool === 'projscan_understand') return understandKeywordWeight(keyword);
  if (tool === 'projscan_feedback_intake') return feedbackKeywordWeight(keyword);
  return undefined;
}

function privacyKeywordWeight(keyword: string): number | undefined {
  if (PRIVACY_WEIGHT_THREE_KEYWORDS.has(keyword)) return 3;
  if (PRIVACY_WEIGHT_TWO_KEYWORDS.has(keyword)) return 2;
  return undefined;
}

function understandKeywordWeight(keyword: string): number | undefined {
  return UNDERSTAND_WEIGHT_TWO_KEYWORDS.has(keyword) ? 2 : undefined;
}

function feedbackKeywordWeight(keyword: string): number | undefined {
  if (FEEDBACK_WEIGHT_THREE_KEYWORDS.has(keyword)) return 3;
  if (FEEDBACK_WEIGHT_TWO_KEYWORDS.has(keyword)) return 2;
  return undefined;
}
